### ISSUE TITLE
Market Research: Locations

### ISSUE THREAD

**Issue by kuromasadev** [kuromasadev/PROJ4-GRP2#17]
Provide locations for Food Supply Chain Stages:
- [x] 1. agriculture (raw material supplier) - minimum 25
- [ ] 2. supplier (storing, raw material distributor) - minimum 25
- [ ] 3. production (packaging, processing from raw) - minimum 25
- [ ] 4. transport (LTL, distribution centers) - minimum 25
- [x] 5. consumer (retail stores) - at least 6000

**Comment by doaabarq** [comment]
https://www.nass.usda.gov/Charts_and_Maps/Agricultural_Prices/pricesb.php

**Comment by kuromasadev** [comment]
fantstic - we can use this
